module.exports = function(option){
    return [
        'Running command: /' + option.uid + '/ionic/book-store/hooks/after_prepare/010_add_platform_class.js /' + option.uid + '/ionic/book-store',
        'add to body class: platform-android',
        'Running command: /' + option.uid + '/ionic/book-store/platforms/android/cordova/build',
        'ANDROID_HOME=/gamilms/Android/Sdk',
        'JAVA_HOME=/usr/lib/jvm/java-7-oracle',
        'Running: /' + option.uid + '/ionic/book-store/platforms/android/gradlew cdvBuildDebug -b /' + option.uid + '/ionic/book-store/platforms/android/build.gradle -Dorg.gradle.daemon=true',
        ':preBuild',
        ':compileDebugNdk',
        ':preDebugBuild',
        ':checkDebugManifest',
        ':CordovaLib:compileLint',
        ':CordovaLib:copyDebugLint UP-TO-DATE',
        ':CordovaLib:mergeDebugProguardFiles',
        ':CordovaLib:preBuild',
        ':CordovaLib:preDebugBuild',
        ':CordovaLib:checkDebugManifest',
        ':CordovaLib:prepareDebugDependencies',
        ':CordovaLib:compileDebugAidl',
        ':CordovaLib:compileDebugRenderscript',
        ':CordovaLib:generateDebugBuildConfig',
        ':CordovaLib:generateDebugAssets UP-TO-DATE',
        ':CordovaLib:mergeDebugAssets',
        ':CordovaLib:generateDebugResValues',
        ':CordovaLib:generateDebugResources',
        ':CordovaLib:packageDebugResources',
        ':CordovaLib:processDebugManifest',
        ':CordovaLib:processDebugResources',
        ':CordovaLib:generateDebugSources',
        ':CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.',
        'Note: Recompile with -Xlint:deprecation for details.',
        '',
        ':CordovaLib:processDebugJavaRes UP-TO-DATE',
        ':CordovaLib:packageDebugJar',
        ':CordovaLib:compileDebugNdk',
        ':CordovaLib:packageDebugJniLibs UP-TO-DATE',
        ':CordovaLib:packageDebugLocalJar UP-TO-DATE',
        ':CordovaLib:packageDebugRenderscript UP-TO-DATE',
        ':CordovaLib:bundleDebug',
        ':prepareAndroidCordovaLibUnspecifiedDebugLibrary',
        ':prepareDebugDependencies',
        ':compileDebugAidl',
        ':compileDebugRenderscript',
        ':generateDebugBuildConfig',
        ':generateDebugAssets UP-TO-DATE',
        ':mergeDebugAssets',
        ':generateDebugResValues',
        ':generateDebugResources',
        ':mergeDebugResources',
        ':processDebugManifest',
        ':processDebugResources',
        ':generateDebugSources',
        ':compileDebugJavaNote: /' + option.uid + '/ionic/book-store/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.',
        'Note: Recompile with -Xlint:deprecation for details.',
        '',
        ':preDexDebug',
        ':dexDebug',
        ':processDebugJavaRes UP-TO-DATE',
        ':validateDebugSigning',
        ':packageDebug',
        ':zipalignDebug',
        ':assembleDebug',
        ':cdvBuildDebug',
        '',
        'BUILD SUCCESSFUL',
        '',
        'Total time: ' + (Math.random() * 2 + 15) + ' secs',
        'Built the following apk(s):',
        '    /' + option.uid + '/ionic/book-store/platforms/android/build/outputs/apk/android-debug.apk',
        'public_url: ' + option.store_path + '/' + option.uid + '.apk'
    ];
}
